version: "3.4"

services:

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=myappdb
      - MYSQL_USER=myappuser
      - MYSQL_PASSWORD=myapppassword
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=myappuser
      - PMA_PASSWORD=myapppassword
    depends_on:
      - mariadb

  mail:
    image: schickling/mailcatcher:latest
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  mariadb_data: